name: ServerEconomy
main: com.alazeprt.servereconomy.ServerEconomyPlugin
version: ${version}
author: alazeprt
api-version: 1.13
description: A better system store by command
website: https://github.com/alazeprt/ServerEconomy
depend:
  - Vault
softdepend:
  - GriefPrevention
commands:
  store:
    description: Server Store Command
    aliases:
      - ss
      - serverstore
      - server-store
      - server_store
      - shop
      - servershop
      - server-shop
      - server_shop
permissions:
  servereconomy.store.buy:
    description: Buy item
  servereconomy.store.help:
    description: Help command
  servereconomy.store.list:
    description: List items
  servereconomy.store.search:
    description: Search item
  servereconomy.store.sell:
    description: Sell item
  servereconomy.store.status:
    description: Status command
  servereconomy.store.player:
    description: Basic permissions that players have
    default: true
    children:
      - servereconomy.store.buy
      - servereconomy.store.help
      - servereconomy.store.list
      - servereconomy.store.search
      - servereconomy.store.sell
      - servereconomy.store.status